// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfpezkpugkcenslzkngq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmcGV6a3B1Z2tjZW5zbHprbmdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MzI2MzQsImV4cCI6MjA2ODMwODYzNH0.8b1LGDayk-ckOkrQn57O5DnopP6CulM3zcEWhr1wW-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});